version: '3'

services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=user-tarefa
      - POSTGRES_DB=tarefas
    volumes:
      - ./db/data:/var/lib/postgresql/data
